name: Build and test Go

on:
  push:
    paths-ignore:
    - '.github/**'
    - 'docs/**'
  pull_request:
    paths-ignore:
    - '.github/**'
    - 'docs/**'

jobs:
  build:
    name: Build and test

    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: 'go build -v -o ./triggy ./cmd/triggy'

      - name: Test
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go test -v ./...
